### ISSUE TITLE
Doesn't work on 5.4

### ISSUE THREAD

**Issue by lheintzmann1** [Voidware-Prohibited/ALSXT#70]
Hi,
I've tested ALSXT with your fork of ALS-Refactored on UE 5.4.3 and when I open the project, it doesn't compile, while the Sixze's ALS-Refactored works perfectly.

**Comment by LifeDreamer24** [comment]
Same here...

**Comment by colorindarkness** [comment]
Please include any error messages from the compiler. I just pushed an update last night that should compile in 5.4. Let me know what error messages you receive with the latest update, if any.

**Comment by LifeDreamer24** [comment]
[Locomotion.log](https://github.com/user-attachments/files/16923499/Locomotion.log)

**Comment by colorindarkness** [comment]
@lheintzmann1 @LifeDreamer24 I pushed pushed an update, it should have fixed all the issues. Let me know what error messages you receive now, if any

**Comment by LifeDreamer24** [comment]
[Locomotion.log](https://github.com/user-attachments/files/16925474/Locomotion.log)
Still can't compile sadly

**Comment by colorindarkness** [comment]
@LifeDreamer24 @lheintzmann1 I pushed a new update, this should resolve the 'MARK_PROPERTY_DIRTY_FROM_NAME': identifier not found errors. The remaining error is weird and I cannot reproduce. If I add an include statement, it introduces a circular dependency issue, which the existing forward declaration should already resolve.
What IDE are you using? Are you using ReSharper? Any particular "strict" settings you are using?

**Comment by LifeDreamer24** [comment]
Eyy great news! After cleaning the project and recompiling everything (ALS Refactored + ALSXT) it compiled!
[Locomotion.log](https://github.com/user-attachments/files/16942347/Locomotion.log)

**Comment by colorindarkness** [comment]
@LifeDreamer24  @lheintzmann1 Excellent, glad to hear it. I switched to non-unity builds until we reach stable releases, so that I don't miss any include statements.
